### PR TITLE
Add version information to prevent additional '/' page view on load

### PR DESCRIPTION
**Pull request by ezequielc**
@Rise-Vision/apps I managed to fix the double page view issue, but unfortunately I can't get the build to pass. It works fine locally. Any suggestions? Thanks

Staged at https://apps-stage-1.risevision.com

### CODE REVIEW

**Comment by olegrise** [comment]
@ezequielc looks like Lint is failing. I would just add a corresponding rule for this case https://eslint.org/docs/rules/camelcase

**Comment by alex-deaconu** [comment]
@ezequielc could it be that a dependency is missing or has been updated without our knowledge? Did you try to run the tests after updating bower? The e2e test seems unrelated. Thanks.

**Comment by ezequielc** [comment]
Thanks @olegrise, the lint issue is an existing warning and does not stop the build process. The main issue here is a failing e2e test. 
By the way, this fix will also solve [the card](https://trello.com/c/SJzPX5lt/3194-fix-double-pageview-problem-on-store) that Ghislaine added to Store board. 
Once I manage to fix the build, I will tag a new CH version and you can use it. 

@alex-deaconu Yes, I updated bower locally and no luck. Unfortunately there is no screenshot in the artifacts here.

Thanks

**Comment by ezequielc** [comment]
@alex-deaconu @fjvallarino @olegrise Thanks for the help! PR is ready for review.

**Comment by alex-deaconu** [comment]
@ezequielc looks good to me 👍 . Curious, is v4.0.0 of the snippet newer or older? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu It is the newest. Thanks

**Comment by olegrise** [comment]
👍

**Pull request merged**
