### PR TITLE
Timeline component

### PR DESCRIPTION
**Pull request by alex-deaconu**
Added directive for component with first iteration of the UX
Modified UX by adding a recurrence checkbox

Fixed issue with synchronized fields
Fixed issues with time picker and date component
Split timeline data setting/saving to a service
Added validation

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi please review. Thanks!

**Comment by rodrigopavezi** [comment]
@alex-deaconu I added some comments but looks good overall. :+1:

**Comment by alex-deaconu** [comment]
@rodrigopavezi fixed the issues raised in the comments. Re bug w/ endDate validation you brought up earlier, will investigate and fix in a separate PR. Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu awesome. Good man!! :+1:

**Pull request merged**
