### PR TITLE
Add optional registration route and refactor routes

### PR DESCRIPTION
**Pull request by alex-deaconu**
Fix unregistered route issues

Use common partial for auth states

Simplifying how the state parameter is added
Add param to route if needed

### CODE REVIEW

**Comment by alex-deaconu** [comment]
These are the changes I'm proposing for routing & registration updates.

Staged at https://apps-stage-3.risevision.com

Unfortunately CCI build is failing due to a Unix dependency error; hopefully it will be fixed shortly.

@ezequielc @fjvallarino please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I tried to reset password on stage-3 and got:
Error: Could not resolve 'common.auth.unauthorized.final' from state 'common.auth.resetpassword'.
Could you take a look. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc good catch. Issue should be fixed in latest commit. Also re-staged.

Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc @fjvallarino latest commit fixes issues with storage-selector.html.

Basically, upon receiving the credentials from Google, the page redirects from root `/` to `/storage-selector.html` which is a separate page. Here, the page should load the saved state. This was not happening; `_restoreState` was not called as part of the controller. Moved out of controller to execute all the time (as it was before in userState).

To verify, you can access https://apps-stage-3.risevision.com/storage-selector.html#/

Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Previous issue is fixed, however I found a new one. 
It doesn't show the success messages when updating password or confirming account ([Trello card](https://trello.com/c/5j2vIfVP/2696-ch-show-messages-to-user-after-password-changed-account-confirmed-1)). Thanks

**Comment by ezequielc** [comment]
@alex-deaconu Also, https://apps-stage-3.risevision.com/signup shows Sign In page instead of Sign Up. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc good catch on both counts. The issues should now be corrected, and re-staged. To summarize:

The issue with `/signup` is that I had previously configured the Sign In page to be the default page when unauthenticated. 

Addressed the issue of the messages not showing up. And updated the text as suggested in the doc.

Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc with @fjvallarino's help we were able to resolve the issues with the registration modal. Branch is now restaged and should have all the issues fixed. Please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Looks great, I tested and everything is working as intended. Thanks for fixing!
Only one minor styling issue, in the Add User modal, Username field doesn't have the correct size. Cheers!

**Comment by alex-deaconu** [comment]
@ezequielc got it. Wondering if I could fix that in a subsequent PR as it is an existing issue. Thoughts? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Good with me 👍

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
