### PR TITLE
[feature] Moving confirm-instance to components

### PR DESCRIPTION
**Pull request by alex-deaconu**
Moved this as it is common to displays and schedules apps.

@rodrigopavezi please review. Thanks.

### CODE REVIEW

**Comment by rodrigopavezi** [comment]
LG :+1:

**Comment by olegrise** [comment]
@alex-deaconu @rodrigopavezi what do you think about addding a `readme.md` file into each compenent folder? For example I'm not sure what this component is for and how it looks when it's rendered. BTW, why is it called `confirm-instance`? Why instance?

**Comment by alex-deaconu** [comment]
@olegrise `confirm-instance` is the controller for the confirm message box. It's basically a simplification for the ui-bootstrap component, which always requires a controller to function. It is used in the following manner:

```
        $scope.modalInstance = $modal.open({
          templateUrl: 'partials/confirm-modal.html',
          controller: 'confirmInstance',
          windowClass: 'modal-custom',
          resolve: {
            confirmationTitle: function () {
              return 'schedules-app.details.deleteTitle';
            },
            confirmationMessage: function () {
              return 'schedules-app.details.deleteWarning';
            },
            confirmationButton: function () {
              return 'common.delete-forever';
            },
            cancelButton: null
          }
        });

        $scope.modalInstance.result.then(function () {
          // do what you need if user presses ok
          _delete();
        }, function () {
          // do what you need to do if user cancels
        });
```

re: readme.md's for each component, that would be a great idea. However, looking at the apps backlog I'm not sure where it would fit in the timeline. I will add an issue to the repository for this task. Thanks.

**Comment by olegrise** [comment]
@alex-deaconu got it. Thanks.

**Pull request merged**
