### PR TITLE
Added an id configuration to the search filter

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alex-deaconu please review. I have added it so we can use the id on the e2e tests. cheers

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi is it necessary for this `id` to be configurable? 

Also, curious, why do you prefer to use id's and not classes?

Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu it is necessary to avoid for instance what happens with the spinner. We can then set an id for the specific element so it is easy to find it on the DOM. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi okay. I still think that by using CSS selectors you can avoid this hassle (including the spinner issue), but that's my opinion. 

By the way, you need to include the build results. 

Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu What I see is that if there is two elements with the same class the webdriver will pick one of them and throw a warning about that. Let's say I want to enter some text in one of the fields but it is not he one webdriver has chosen. That is why ids can resolves this situation. Looking at the google auth pages all the elements have ids so it was easy to implement e2e for that. I think it is a good practice to add ids to elements. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi okay. Will follow your lead on this. Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu cool, thanks. Added built files. cheers

**Comment by alex-deaconu** [comment]
LG :+1: . Thanks!

**Pull request merged**
