### PR TITLE
Add delay for intial list load

### PR DESCRIPTION
**Pull request by alex-deaconu**
@rodrigopavezi this seems to work pretty consistently. Please review. Thanks!

### CODE REVIEW

**Comment by olegrise** [comment]
@alex-deaconu  I have similar situation in one of the Store e2e tests. I started with `browser.sleep(500);` and gradually increased it to `browser.sleep(8000);`. 500 ms worked fine most of the time, but there were days when test was consistently failing. I'm still looking for a better option, something that is event driven rather than based on static timeout. I don't think this information helps you, but I just wanted to share my pain :)

**Comment by alex-deaconu** [comment]
@olegrise interesting. Thanks for bringing this up.

I think @rodrigopavezi is the expert on this, but from what I've seen, as an alternative to `browser.sleep()`, there's `browser.wait()`, which will allow you to specifically trigger the action on an event or when an element is present/visible, etc. Here are some examples of how it's used in common-e2e: https://github.com/Rise-Vision/rv-common-e2e/blob/master/lib/common/helper.js. 

Other than that, I don't know why these seemingly synchronous events seem to cause so many issues with timeouts. However, I just hate that every couple of weeks we have to stop and spend some time tweaking e2e tests. It seems very unstable.

@rodrigopavezi @ezequielc thoughts?

Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu I see your point. I think the best is to use the browser wait. It still has a timeout though. In the helper function it has a timeout of 10s. I reduced that from 20s which was on the original code I took as base. I think 10 seconds is a pretty good timeout. If it goes over it, I believe there is something wrong with the app and we should work on the performance. I see, for instance, some testing failing because of the bug where the login does not happen and the spinner stays on forever. So, in this case there is nothing we can do besides fixing the underline login issue.

For now it is okay to use browser.sleep here on the components but I think we should change it to use the rv-common-e2e helper functions.

Re. e2e test in general. I have worked with different libraries from java to javascript. Timeout issues always happen specially when there is integration with backend systems. I think we have to keep tuning them and fix performance issues when it is case. 

cheers

:+1:

**Comment by olegrise** [comment]
@alex-deaconu I haven't tried `browser.wait()` yet, but I saw it was used in `helper.js`. I'm very curious to try it out. Thanks.

**Pull request merged**
